logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtg
    username: postgres
    password: Masterhost25
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  security:
    user:
      roles: USER

